default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: tokiya0421
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ekibank_development

test:
  <<: *default
  database: ekibank_test

production:
  <<: *default
  database: ekibank_production
  username: ekibank
  password: <%= ENV['EKIBANK_DATABASE_PASSWORD'] %>
