default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_DEV_NAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ekibank_development

test:
  <<: *default
  database: ekibank_test

production:
  <<: *default
  database: ekibank_production
  username: <%= ENV['DATABASE_DEV_NAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
