Question.create(content: '希望する間取りは？', created_at: now(), updated_at: now())
Question.create(content: '家賃の予算は？', created_at: now(), updated_at: now())
Question.create(content: '購入する不動産の種別は？', created_at: now(), updated_at: now())
Question.create(content: '購入する不動産の予算は？', created_at: now(), updated_at: now())
Question.create(content: '通勤通学の目的地の最寄駅は？', created_at: now(), updated_at: now())
Question.create(content: '通勤通学時の希望する移動時間は？', created_at: now(), updated_at: now())
Question.create(content: '趣味などでよく行く場所の最寄駅は？', created_at: now(), updated_at: now())
Question.create(content: '趣味などでよく行く場所への希望する移動時間は？', created_at: now(), updated_at: now())
Question.create(content: '駅前の雰囲気はどちらが好み？', created_at: now(), updated_at: now())
Question.create(content: '駅前にスポーツジムは必須？', created_at: now(), updated_at: now())
Question.create(content: '駅前にスターバックスコーヒーは必須？', created_at: now(), updated_at: now())
Question.create(content: '駅前にマクドナルドは必須？', created_at: now(), updated_at: now())
Question.create(content: '駅前に餃子の王将は必須？', created_at: now(), updated_at: now())
Question.create(content: '駅前に食べログの評価が3.5以上のお店は必須？', created_at: now(), updated_at: now())
Question.create(content: '駅前に23時まで営業しているスーパーマーケットは必須？', created_at: now(), updated_at: now())
Question.create(content: '駅の近くに大きな公園は必須？', created_at: now(), updated_at: now())
Question.create(content: '駅の近くに図書館は必須？', created_at: now(), updated_at: now())
Question.create(content: '駅の近くに公衆浴場やサウナは必須？', created_at: now(), updated_at: now())

Answer.create(question_id: 1, content: '5万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '6万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '7万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '8万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '9万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '10万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '11万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '12万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '13万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '14万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '15万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '16万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '17万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '18万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '19万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '20万円台', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '21~25万円', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '26~30万円', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '31~35万円', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '36~40万円', created_at: now(), updated_at: now())
Answer.create(question_id: 1, content: '41万円以上', created_at: now(), updated_at: now())
Answer.create(question_id: 2, content: '戸建', created_at: now(), updated_at: now())
Answer.create(question_id: 2, content: '土地', created_at: now(), updated_at: now())
Answer.create(question_id: 2, content: 'マンション', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '1000万円以下', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '1000~1500万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '1600~2000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '2100~2500万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '2600~3000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '3100~3500万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '3600~4000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '4100~4500万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '4600~5000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '5100~5500万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '5600~6000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '6100~6500万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '6600~7000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '7100~7500万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '7600~8000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '8100~9000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '9100~10000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '11000~15000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '16000~20000万円', created_at: now(), updated_at: now())
Answer.create(question_id: 3, content: '20000万円以上', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '5分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '10分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '15分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '20分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '25分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '30分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '35分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '40分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '45分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '50分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '55分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '60分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '75分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '90分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '105分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 5, content: '120分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '5分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '10分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '15分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '20分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '25分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '30分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '35分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '40分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '45分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '50分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '55分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '60分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '75分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '90分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '105分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 7, content: '120分以内', created_at: now(), updated_at: now())
Answer.create(question_id: 8, content: '静か', created_at: now(), updated_at: now())
Answer.create(question_id: 8, content: 'にぎやか', created_at: now(), updated_at: now())
Answer.create(question_id: 9, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 9, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 10, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 10, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 11, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 11, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 12, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 12, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 13, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 13, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 14, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 14, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 15, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 15, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 16, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 16, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 17, content: '必須', created_at: now(), updated_at: now())
Answer.create(question_id: 17, content: '必須ではない', created_at: now(), updated_at: now())
Answer.create(question_id: 18, content: 'ワンルーム', created_at: now(), updated_at: now())
Answer.create(question_id: 18, content: '1K/1DK', created_at: now(), updated_at: now())
Answer.create(question_id: 18, content: '1LDK/2K/2DK', created_at: now(), updated_at: now())
Answer.create(question_id: 18, content: '2LDK/3K/3Dk', created_at: now(), updated_at: now())
Answer.create(question_id: 18, content: '3LDK/4K以上', created_at: now(), updated_at: now())
