Question.create(content: '希望する間取りは？')
Question.create(content: '家賃の予算は？')
Question.create(content: '住みたいエリアは？')
Question.create(content: '購入する不動産の種別は？')
Question.create(content: '購入する不動産の予算は？')
Question.create(content: '通勤通学の目的地の最寄駅は？')
Question.create(content: '通勤通学時の希望する移動時間は？')
Question.create(content: '趣味などでよく行く場所の最寄駅は？')
Question.create(content: '趣味などでよく行く場所への希望する移動時間は？')
Question.create(content: '駅前にスポーツジムは必須？')
Question.create(content: '駅前にスターバックスコーヒーは必須？')
Question.create(content: '駅前にマクドナルドは必須？')
Question.create(content: '駅前に餃子の王将は必須？')
Question.create(content: '駅前に23時まで営業しているスーパーマーケットは必須？')
Question.create(content: '駅の近くに大きな公園は必須？')
Question.create(content: '駅の近くに図書館は必須？')
Question.create(content: '駅の近くに公衆浴場やサウナは必須？')

Answer.create(question_id: 1, content: '5万円台')
Answer.create(question_id: 1, content: '6万円台')
Answer.create(question_id: 1, content: '7万円台')
Answer.create(question_id: 1, content: '8万円台')
Answer.create(question_id: 1, content: '9万円台')
Answer.create(question_id: 1, content: '10万円台')
Answer.create(question_id: 1, content: '11万円台')
Answer.create(question_id: 1, content: '12万円台')
Answer.create(question_id: 1, content: '13万円台')
Answer.create(question_id: 1, content: '14万円台')
Answer.create(question_id: 1, content: '15万円台')
Answer.create(question_id: 1, content: '16万円台')
Answer.create(question_id: 1, content: '17万円台')
Answer.create(question_id: 1, content: '18万円台')
Answer.create(question_id: 1, content: '19万円台')
Answer.create(question_id: 1, content: '20万円台')
Answer.create(question_id: 1, content: '21~25万円')
Answer.create(question_id: 1, content: '26~30万円')
Answer.create(question_id: 1, content: '31~35万円')
Answer.create(question_id: 1, content: '36~40万円')
Answer.create(question_id: 1, content: '41万円以上')
Answer.create(question_id: 2, content: '戸建')
Answer.create(question_id: 2, content: '土地')
Answer.create(question_id: 2, content: 'マンション')
Answer.create(question_id: 3, content: '1000万円以下')
Answer.create(question_id: 3, content: '1000~1500万円')
Answer.create(question_id: 3, content: '1600~2000万円')
Answer.create(question_id: 3, content: '2100~2500万円')
Answer.create(question_id: 3, content: '2600~3000万円')
Answer.create(question_id: 3, content: '3100~3500万円')
Answer.create(question_id: 3, content: '3600~4000万円')
Answer.create(question_id: 3, content: '4100~4500万円')
Answer.create(question_id: 3, content: '4600~5000万円')
Answer.create(question_id: 3, content: '5100~5500万円')
Answer.create(question_id: 3, content: '5600~6000万円')
Answer.create(question_id: 3, content: '6100~6500万円')
Answer.create(question_id: 3, content: '6600~7000万円')
Answer.create(question_id: 3, content: '7100~7500万円')
Answer.create(question_id: 3, content: '7600~8000万円')
Answer.create(question_id: 3, content: '8100~9000万円')
Answer.create(question_id: 3, content: '9100~10000万円')
Answer.create(question_id: 3, content: '11000~15000万円')
Answer.create(question_id: 3, content: '16000~20000万円')
Answer.create(question_id: 3, content: '20000万円以上')
Answer.create(question_id: 5, content: '10分以内')
Answer.create(question_id: 5, content: '20分以内')
Answer.create(question_id: 5, content: '30分以内')
Answer.create(question_id: 5, content: '40分以内')
Answer.create(question_id: 5, content: '50分以内')
Answer.create(question_id: 5, content: '60分以内')
Answer.create(question_id: 5, content: '70分以内')
Answer.create(question_id: 5, content: '80分以内')
Answer.create(question_id: 5, content: '90分以内')
Answer.create(question_id: 7, content: '10分以内')
Answer.create(question_id: 7, content: '20分以内')
Answer.create(question_id: 7, content: '30分以内')
Answer.create(question_id: 7, content: '40分以内')
Answer.create(question_id: 7, content: '50分以内')
Answer.create(question_id: 7, content: '60分以内')
Answer.create(question_id: 7, content: '70分以内')
Answer.create(question_id: 7, content: '80分以内')
Answer.create(question_id: 7, content: '90分以内')
Answer.create(question_id: 9, content: '必須')
Answer.create(question_id: 9, content: '必須ではない')
Answer.create(question_id: 10, content: '必須')
Answer.create(question_id: 10, content: '必須ではない')
Answer.create(question_id: 11, content: '必須')
Answer.create(question_id: 11, content: '必須ではない')
Answer.create(question_id: 12, content: '必須')
Answer.create(question_id: 12, content: '必須ではない')
Answer.create(question_id: 13, content: '必須')
Answer.create(question_id: 13, content: '必須ではない')
Answer.create(question_id: 14, content: '必須')
Answer.create(question_id: 14, content: '必須ではない')
Answer.create(question_id: 15, content: '必須')
Answer.create(question_id: 15, content: '必須ではない')
Answer.create(question_id: 16, content: '必須')
Answer.create(question_id: 16, content: '必須ではない')
Answer.create(question_id: 17, content: '必須')
Answer.create(question_id: 17, content: '必須ではない')
Answer.create(question_id: 18, content: 'ワンルーム')
Answer.create(question_id: 18, content: '1K/1DK')
Answer.create(question_id: 18, content: '1LDK/2K/2DK')
Answer.create(question_id: 18, content: '2LDK/3K/3Dk')
Answer.create(question_id: 18, content: '3LDK/4K以上')
Answer.create(question_id: 19, content: '東京都')
Answer.create(question_id: 19, content: '神奈川県')
Answer.create(question_id: 19, content: '埼玉県')
Answer.create(question_id: 19, content: '千葉県')
