// 各importはpacks/application.jsで呼び出される
import 'bootstrap';
import './show_12';
import './devise_page'
import './pages_show';
import './questions_show_1';
import './questions_show_2';
import './questions_show_3';
import './questions_show_4';
import './questions_show_5';
import './questions_show_6';
import './questions_show_7';
import './questions_show_8';
import './questions_show_9';
import './questions_show_10';
import './questions_show_11';
import './questions_show_12';
import './back_search';
import './answers_show';